/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AllProjectsRouteImport } from './routes/all-projects'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as ErrTooManyTabsRouteImport } from './routes/err-too-many-tabs'
import { Route as IncognitoRouteImport } from './routes/incognito'
import { Route as LocalhostRouteImport } from './routes/localhost'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PressKitRouteImport } from './routes/press-kit'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AllProjectsRoute = AllProjectsRouteImport.update({
  id: '/all-projects',
  path: '/all-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrTooManyTabsRoute = ErrTooManyTabsRouteImport.update({
  id: '/err-too-many-tabs',
  path: '/err-too-many-tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IncognitoRoute = IncognitoRouteImport.update({
  id: '/incognito',
  path: '/incognito',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalhostRoute = LocalhostRouteImport.update({
  id: '/localhost',
  path: '/localhost',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PressKitRoute = PressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-projects': typeof AllProjectsRoute
  '/draft': typeof DraftRoute
  '/err-too-many-tabs': typeof ErrTooManyTabsRoute
  '/incognito': typeof IncognitoRoute
  '/localhost': typeof LocalhostRoute
  '/notes': typeof NotesRoute
  '/press-kit': typeof PressKitRoute
  '/work': typeof WorkRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-projects': typeof AllProjectsRoute
  '/draft': typeof DraftRoute
  '/err-too-many-tabs': typeof ErrTooManyTabsRoute
  '/incognito': typeof IncognitoRoute
  '/localhost': typeof LocalhostRoute
  '/notes': typeof NotesRoute
  '/press-kit': typeof PressKitRoute
  '/work': typeof WorkRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-projects': typeof AllProjectsRoute
  '/draft': typeof DraftRoute
  '/err-too-many-tabs': typeof ErrTooManyTabsRoute
  '/incognito': typeof IncognitoRoute
  '/localhost': typeof LocalhostRoute
  '/notes': typeof NotesRoute
  '/press-kit': typeof PressKitRoute
  '/work': typeof WorkRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/all-projects'
    | '/draft'
    | '/err-too-many-tabs'
    | '/incognito'
    | '/localhost'
    | '/notes'
    | '/press-kit'
    | '/work'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/all-projects'
    | '/draft'
    | '/err-too-many-tabs'
    | '/incognito'
    | '/localhost'
    | '/notes'
    | '/press-kit'
    | '/work'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/all-projects'
    | '/draft'
    | '/err-too-many-tabs'
    | '/incognito'
    | '/localhost'
    | '/notes'
    | '/press-kit'
    | '/work'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllProjectsRoute: typeof AllProjectsRoute
  DraftRoute: typeof DraftRoute
  ErrTooManyTabsRoute: typeof ErrTooManyTabsRoute
  IncognitoRoute: typeof IncognitoRoute
  LocalhostRoute: typeof LocalhostRoute
  NotesRoute: typeof NotesRoute
  PressKitRoute: typeof PressKitRoute
  WorkRoute: typeof WorkRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-projects': {
      id: '/all-projects'
      path: '/all-projects'
      fullPath: '/all-projects'
      preLoaderRoute: typeof AllProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/err-too-many-tabs': {
      id: '/err-too-many-tabs'
      path: '/err-too-many-tabs'
      fullPath: '/err-too-many-tabs'
      preLoaderRoute: typeof ErrTooManyTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incognito': {
      id: '/incognito'
      path: '/incognito'
      fullPath: '/incognito'
      preLoaderRoute: typeof IncognitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localhost': {
      id: '/localhost'
      path: '/localhost'
      fullPath: '/localhost'
      preLoaderRoute: typeof LocalhostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-kit': {
      id: '/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof PressKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllProjectsRoute: AllProjectsRoute,
  DraftRoute: DraftRoute,
  ErrTooManyTabsRoute: ErrTooManyTabsRoute,
  IncognitoRoute: IncognitoRoute,
  LocalhostRoute: LocalhostRoute,
  NotesRoute: NotesRoute,
  PressKitRoute: PressKitRoute,
  WorkRoute: WorkRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
